# Generated by Django 4.1.4 on 2022-12-23 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_travel_travelimages_delete_tour'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemsTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('card', models.BigIntegerField()),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ManyToManyField(through='order.OrderItemsTravel', to='travel.travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordertravels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitemstravel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='travelitems', to='order.ordertravel'),
        ),
        migrations.AddField(
            model_name='orderitemstravel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='travelitems', to='travel.travel'),
        ),
    ]
